### ISSUE TITLE
NoSuchMethodError: android.media.audiofx.Visualizer.setScalingMode

### ISSUE THREAD

**Issue by jmimohsin** [bogerchan/Nier-Visualizer#14]
Hi,

Please check the below error:-

```java
Fatal Exception: java.lang.NoSuchMethodError: android.media.audiofx.Visualizer.setScalingMode
       at me.bogerchan.niervisualizer.NierVisualizerManager.init(Unknown Source)
       at com.radios.india.RadioStationActivity.setVisual(Unknown Source)
       at com.radios.india.RadioStationActivity.onCreate(Unknown Source)
       at android.app.Activity.performCreate(Activity.java:4470)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1053)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1934)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1995)
       at android.app.ActivityThread.access$600(ActivityThread.java:128)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1161)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4517)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:993)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:760)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by jmimohsin** [comment]
![image](https://user-images.githubusercontent.com/4438426/45914387-3e886a00-be62-11e8-920b-2fecd9b6da51.png)

![image](https://user-images.githubusercontent.com/4438426/45914397-55c75780-be62-11e8-9e36-d2bdedef88d0.png)

**Comment by bogerchan** [comment]
Hi, `setScalingMode ` is required by api >= 16, but it is also throw `java.lang.NoSuchMethodError` in 5.x above, am I understand right ?

**Comment by jmimohsin** [comment]
I understand API Level issue but it should not come in Android 6 or 7. 

Am I right?

Or you can use try catch because crash is not good better not to work.

**Comment by bogerchan** [comment]
OK, I will catch it when call `setScalingMode `,  please try v0.1.1

**Comment by jmimohsin** [comment]
still getting error :(

![image](https://user-images.githubusercontent.com/4438426/47601034-32a34100-d9e8-11e8-91d6-119bd2b4a3f4.png)

![image](https://user-images.githubusercontent.com/4438426/47601035-3d5dd600-d9e8-11e8-9d74-aa879d8b289e.png)

**Comment by bogerchan** [comment]
I will try catch it and add  a return value for `init()` method, you can use it to know whether the library has been initialized successfully. I will fix it in next weekend. :)

**Comment by jmimohsin** [comment]
OK Thanks

**Comment by bogerchan** [comment]
Please try `v0.1.2`.  :)

**Comment by jmimohsin** [comment]
thanks...

**Comment by jmimohsin** [comment]
I have updated app tomorrow got this result....

![image](https://user-images.githubusercontent.com/4438426/48604452-ec664f80-e99f-11e8-920f-0a2acb0522e3.png)

Now getting these errors.

```java
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{coders.hub.fm.radio/com.radios.india.RadioStationActivity}: android.content.res.Resources$NotFoundException: File res/raw/av_workaround_1min.mp3 from drawable resource ID #0x7f0e0000
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

```java
Caused by android.content.res.Resources$NotFoundException: File res/raw/av_workaround_1min.mp3 from drawable resource ID #0x7f0e0000
       at android.content.res.ResourcesImpl.openRawResourceFd(ResourcesImpl.java:317)
       at android.content.res.Resources.openRawResourceFd(Resources.java:1307)
       at android.media.MediaPlayer.create(MediaPlayer.java:1033)
       at android.media.MediaPlayer.create(MediaPlayer.java:1012)
       at com.cleveroad.audiovisualization.VisualizerWrapper.(Unknown Source:6)
       at com.cleveroad.audiovisualization.VisualizerDbmHandler.(Unknown Source:13)
       at com.cleveroad.audiovisualization.DbmHandler$Factory.newVisualizerHandler(Unknown Source:2)
       at com.radios.india.RadioStationActivity.setVisual(Unknown Source:42)
       at com.radios.india.RadioStationActivity.onCreate(Unknown Source:356)
       at android.app.Activity.performCreate(Activity.java:7183)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

```java
Caused by java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
       at android.content.res.AssetManager.openNonAssetFdNative(AssetManager.java)
       at android.content.res.AssetManager.openNonAssetFd(AssetManager.java:501)
       at android.content.res.ResourcesImpl.openRawResourceFd(ResourcesImpl.java:315)
       at android.content.res.Resources.openRawResourceFd(Resources.java:1307)
       at android.media.MediaPlayer.create(MediaPlayer.java:1033)
       at android.media.MediaPlayer.create(MediaPlayer.java:1012)
       at com.cleveroad.audiovisualization.VisualizerWrapper.(Unknown Source:6)
       at com.cleveroad.audiovisualization.VisualizerDbmHandler.(Unknown Source:13)
       at com.cleveroad.audiovisualization.DbmHandler$Factory.newVisualizerHandler(Unknown Source:2)
       at com.radios.india.RadioStationActivity.setVisual(Unknown Source:42)
       at com.radios.india.RadioStationActivity.onCreate(Unknown Source:356)
       at android.app.Activity.performCreate(Activity.java:7183)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```


```java
Fatal Exception: java.lang.NoSuchMethodError: android.media.audiofx.Visualizer.setMeasurementMode
       at me.bogerchan.niervisualizer.NierVisualizerManager.init(Unknown Source)
       at com.radios.india.RadioStationActivity.setVisual(Unknown Source)
       at com.radios.india.RadioStationActivity.onCreate(Unknown Source)
       at android.app.Activity.performCreate(Activity.java:5326)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2225)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2316)
       at android.app.ActivityThread.access$700(ActivityThread.java:158)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1296)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:5365)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by bogerchan** [comment]
Only the last stack trace is Nier's, but the `setMeasurementMode` has been existed since api >= 19, please enable the library in devices which their api >= 19. :)
