### ISSUE TITLE
sometime wrong

### ISSUE THREAD

**Issue by Citrussss** [bogerchan/Nier-Visualizer#36]
kotlin.UninitializedPropertyAccessException: lateinit property mDestWaveData has not been initialized
        at me.bogerchan.niervisualizer.util.KeyFrameMaker.updateWaveData(KeyFrameMaker.kt:32)
        at me.bogerchan.niervisualizer.core.NierVisualizerRenderWorker.processUpdateWaveEvent(NierVisualizerRenderWorker.kt:118)
        at me.bogerchan.niervisualizer.core.NierVisualizerRenderWorker.access$processUpdateWaveEvent(NierVisualizerRenderWorker.kt:22)
        at me.bogerchan.niervisualizer.core.NierVisualizerRenderWorker$mRenderHandler$2$1.handleMessage(NierVisualizerRenderWorker.kt:56)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by bogerchan** [comment]
Thanks for reporting the issues, I would fix it ASAP. : )

**Comment by akshitk007** [comment]
@Citrussss I am facing the same issue Did you find something to handle this issue?

**Comment by Citrussss** [comment]
> @Citrussss I am facing the same issue Did you find something to handle this issue?

i am download code and change it at local .

```
    fun updateWaveData(waveData: ByteArray) {
        if(this::mDestWaveData.isInitialized){//add this line..
            System.arraycopy(waveData, 0, mDestWaveData, 0, mDestWaveData.size)
            System.arraycopy(computedWaveData, 0, mPrevWaveData, 0, mPrevWaveData.size)
//        System.arraycopy(waveData, 0, computedWaveData, 0, computedWaveData.size)
//        System.arraycopy(waveData, 0, mPrevWaveData, 0, mPrevWaveData.size)
            mWaveAnimator.reset()
        }
    }
```

**Comment by olivaresrafael** [comment]
I am facing the same issue when restar activity.

**Comment by sergeykrupenich** [comment]
are there any updates related to the issue?

**Comment by bogerchan** [comment]
Sorry for the late reply, the issue is happened when you are not call the start event, you can call the following codes after the activity is restarted.

```
mVisualizerManager?.start(svWave, mRenderers[idx % mRenderers.size])
```
Next release will fix this issue. : )

**Comment by rameezhandel** [comment]
Thanks for the wonderful library.
when are you releasing the fix for this issue?

**Comment by Citrussss** [comment]
@rameezhandel I dont think so what he would fix it ASAP when he tell  at 2020 but 🐦 咕咕咕(joke!)

**Comment by kishorekumarek** [comment]
> fun updateWaveData(waveData: ByteArray) {
>         if(this::mDestWaveData.isInitialized){//add this line..
>             System.arraycopy(waveData, 0, mDestWaveData, 0, mDestWaveData.size)
>             System.arraycopy(computedWaveData, 0, mPrevWaveData, 0, mPrevWaveData.size)
> //        System.arraycopy(waveData, 0, computedWaveData, 0, computedWaveData.size)
> //        System.arraycopy(waveData, 0, mPrevWaveData, 0, mPrevWaveData.size)
>             mWaveAnimator.reset()
>         }
>     }

@Citrussss this fixed the crash for you?

**Comment by Citrussss** [comment]
sure ，but aren't you an IOS developer？ @kishorekumarek

**Comment by kishorekumarek** [comment]
@Citrussss yes i work on android as well.. :)
